name: lojavirtual
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.6
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  provider: ^4.1.3
  carousel_pro: ^1.0.0
  flutter_staggered_grid_view: ^0.3.0
  transparent_image: ^1.0.0
  alphabet_list_scroll_view: ^1.0.6
  faker: ^1.2.1
  image_picker: ^0.6.7+1
  image_cropper: ^1.2.2
  uuid: ^2.0.4
  dio: ^3.0.9
  brasil_fields: ^0.2.0
  geolocator: ^5.3.2+2
  sliding_up_panel: ^1.0.2
  screenshot: ^0.1.1
  gallery_saver: ^2.0.1
  flutter_signin_button: ^1.0.0
  flutter_facebook_login: ^3.0.0
  url_launcher: ^5.4.11
  map_launcher: ^0.5.0
  flip_card: ^0.4.4
  mask_text_input_formatter: ^1.0.7
  credit_card_type_detector: ^1.1.0
  keyboard_actions: ^3.2.1+1
  cloud_functions: ^0.5.0
  cpf_cnpj_validator: ^1.0.5
  firebase_messaging: ^6.0.16
  flushbar: ^1.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.2.0

flutter:


  uses-material-design: true